language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t dbasidd/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dbasidd/docker-react npm run test
